### ISSUE TITLE
In ubuntu 16.04 cannot import opus functions

### ISSUE THREAD

**Issue by Ioaer** [Zuzu-Typ/PyOgg#16]
Tested using python versions 2.7 and 3.5

**Comment by Zuzu-Typ** [comment]
Do you have an opus library installed on your system?

**Comment by Ioaer** [comment]
If you mean has pip installed pyogg, then yes.

**Comment by Zuzu-Typ** [comment]
Pyogg requires your system to have the [url=https://github.com/xiph/opus]opus libraries[/url] installed on your system, as pyogg only provides the bindings to them. 
On Windows they are shipped with the package, on linux you're required to build them yourself, because of the variety of OSes and configurations.
