### ISSUE TITLE
vorbis_encode_init lookup in wrong library

### ISSUE THREAD

**Issue by eisenlaub** [Zuzu-Typ/PyOgg#5]
PyOgg is looking for the `vorbis_encode_init` symbol in the wrong library. It tries to find the function in the `libvorbis.so` library but the symbol is exported by `libvorbisenc.so` 

```
$ nm -D /usr/lib/libvorbisenc.so
00000000002b20b8 B __bss_start
                 U calloc
                 w __cxa_finalize
00000000002b20b8 D _edata
00000000002b20c0 B _end
00000000000161a8 T _fini
                 w __gmon_start__
0000000000013ab8 T _init
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 w _Jv_RegisterClasses
                 U malloc
                 U __stack_chk_fail
0000000000015c60 T vorbis_encode_ctl
0000000000015c10 T vorbis_encode_init
0000000000015a00 T vorbis_encode_init_vbr
0000000000014470 T vorbis_encode_setup_init
0000000000015a50 T vorbis_encode_setup_managed
0000000000015930 T vorbis_encode_setup_vbr
                 U vorbis_info_clear
```

**Comment by Zuzu-Typ** [comment]
Yes it does. I didn't know you could build libvorbisenc alone, because the win32 version of libvorbis includes libvorbisenc.
![vorbisenc](https://user-images.githubusercontent.com/20467351/29522511-a90b1d4e-8689-11e7-8bd8-3600c0e03a73.png)

I'll make it so that it uses libvorbisenc if present and libvorbis otherwise.

**Comment by eisenlaub** [comment]
Works, thanks for the fast fix. 👍
